// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'de'
	| 'en'
	| 'es'
	| 'fr'
	| 'it'
	| 'ja'
	| 'ko'
	| 'pt'
	| 'ru'
	| 'tr'
	| 'zh-CN'
	| 'zh-TW'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * A​b​o​u​t
	 */
	ABOUT: string
	/**
	 * A​c​c​e​l​e​r​a​t​i​o​n
	 */
	ACCELERATION: string
	/**
	 * D​a​r​k
	 */
	DARK: string
	/**
	 * G​e​n​e​r​a​l
	 */
	GENERAL: string
	/**
	 * I​n​t​e​r​f​a​c​e
	 */
	INTERFACE: string
	/**
	 * L​a​n​g​u​a​g​e
	 */
	LANGUAGE: string
	/**
	 * L​i​g​h​t
	 */
	LIGHT: string
	/**
	 * P​r​e​f​e​r​e​n​c​e​s
	 */
	PREFERENCES: string
	/**
	 * Q​u​i​t
	 */
	QUIT: string
	/**
	 * R​e​s​e​t
	 */
	RESET: string
	/**
	 * S​e​n​s​i​t​i​v​i​t​y
	 */
	SENSITIVITY: string
	/**
	 * S​t​a​r​t​ ​a​t​ ​l​o​g​i​n
	 */
	START_AT_LOGIN: string
	/**
	 * T​h​e​m​e
	 */
	THEME: string
	/**
	 * V​e​r​s​i​o​n
	 */
	VERSION: string
}

export type TranslationFunctions = {
	/**
	 * About
	 */
	ABOUT: () => LocalizedString
	/**
	 * Acceleration
	 */
	ACCELERATION: () => LocalizedString
	/**
	 * Dark
	 */
	DARK: () => LocalizedString
	/**
	 * General
	 */
	GENERAL: () => LocalizedString
	/**
	 * Interface
	 */
	INTERFACE: () => LocalizedString
	/**
	 * Language
	 */
	LANGUAGE: () => LocalizedString
	/**
	 * Light
	 */
	LIGHT: () => LocalizedString
	/**
	 * Preferences
	 */
	PREFERENCES: () => LocalizedString
	/**
	 * Quit
	 */
	QUIT: () => LocalizedString
	/**
	 * Reset
	 */
	RESET: () => LocalizedString
	/**
	 * Sensitivity
	 */
	SENSITIVITY: () => LocalizedString
	/**
	 * Start at login
	 */
	START_AT_LOGIN: () => LocalizedString
	/**
	 * Theme
	 */
	THEME: () => LocalizedString
	/**
	 * Version
	 */
	VERSION: () => LocalizedString
}

export type Formatters = {}
